name: NodeJS with Webpack

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [18.x, 20.x, 22.x]

    steps:
    - uses: actions/checkout@v4

    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v4
      with:
        node-version: ${{ matrix.node-version }}

    - name: Generate static site
      run: |
        npm install
        npm run generate
        cp -r .output/public ..

    - name: Checkout and copy
      run: |
        git config --global user.name doc-site
        git switch public
        mv ../.output/public/** .
        git add *
        git commit -m 'update built site'
        git push origin public
