name: NodeJS with Webpack

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Use Node.js 20.x
      uses: actions/setup-node@v4
      with:
        node-version: 20.x

    - name: Generate static site
      run: |
        npm install
        npm run generate
        cp -r .output/public ..

    - name: Checkout and copy
      run: |
        git config --global user.name doc-site
        git clone https://github.com/typstdocsinchinese/typstdocsinchinese.github.io.git tt
        cd tt
        git remote set-url origin https://Subilan:${{ secrets.TOKEN }}@github.com/typstdocsinchinese/typstdocsinchinese.github.io
        git switch public
        mv ../.output/public/** .
        git add *
        git commit -m 'update built site'
        git push origin public
